name: Integração Contínua - DevCalc

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build do projeto
        run: mvn clean install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Executar testes
        run: mvn test

  codeql-analysis:
    name: Análise de Segurança com CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java

      - name: Compilar o projeto
        run: mvn clean compile

      - name: Executar análise com CodeQL
        uses: github/codeql-action/analyze@v4

  lint-check:
    name: Lint com Checkstyle
    runs-on: ubuntu-latest
    needs: test # só vai rodar depois que os testes rodarem com esse comando
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: Executar Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Gerar relatório do Checkstyle
        run: mvn site

      - name: Upload do relatório como artefato
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/site/checkstyle.html

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gerar artefato .jar
        run: mvn package
    
  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Mensagem de simulação de deploy
        run: echo "✅ Deploy realizado com sucesso"
