name: Integração Contínua - DevCalc

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build do projeto
        run: mvn clean install

  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml
    with:
      java-version: '17'

  codeql-analysis:
    name: Análise de Segurança com CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java

      - name: Compilar o projeto
        run: mvn clean compile

      - name: Executar análise com CodeQL
        uses: github/codeql-action/analyze@v4
        
  package:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gerar artefato .jar
        run: mvn package
    
  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Mensagem de simulação de deploy
        run: echo "✅ Deploy realizado com sucesso"
