name: TP3 - Uso do GITHUB_TOKEN

on: 
  workflow_dispatch:

permissions:
  issues: write # necess치rio para criar issues

jobs:
  criar-issue-condicional: 
    runs-on: ubuntu-latest

    steps:
      - name: Verificar se PROD_TOKEN est치 definido
        id: verificar
        run: |
          if [ -z "${{ secrets.PROD_TOKEN }}"]; then
            echo "ausente=true" >> $GITHUB_OUTPUT
          else
            echo "ausente=false" >> $GITHUB_OUTPUT
          fi

      - name: Instalar GitHub CLI
        if: steps.verificar.outputs.ausente == 'true'
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Criar issue automaticamente
        if: steps.verificar.outputs.ausente == 'true'
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create \
          --title "游뚿 PROD_TOKEN ausente no reposit칩rio" \
          --body "Foi detectada a aus칡ncia do secret PROD_TOKEN. Verifique a configura칞칚o nas vari치veis do reposit칩rio." \
          --label "ci"