name: TP3 - Runner Auto-Hospedado

on:
  workflow_dispatch:

jobs:
  executar-localmente:
    name: Execução no Runner Local
    runs-on: self-hosted

    steps:
      - name: Exibir SO e Java
        run: |
          echo "Sistema Operacional:"
          uname -a
          echo "Versão do Java:"
          java -version

      - name: Instalar 7zip via Chocolatey (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install 7zip -y
          echo "7zip instalado com sucesso."

      - name: Verificar caminho do 7zip
        if: runner.os == 'Windows'
        run: where 7z || echo "7z não encontrado"
