name: Uso de Variáveis e Secrets

on:
  workflow_dispatch:

jobs:
  mostrar-vars-e-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar variáveis públicas
        run: |
          echo "Modo da aplicação: ${{ vars.APP_MODE }}"
          echo "Email de suporte: ${{ vars.SUPPORT_EMAIL }}"

      - name: Simular uso de segredo (sem exibir o valor)
        run: |
          echo "Autenticando com PROD_TOKEN..."
          echo "${{ secrets.PROD_TOKEN }}" | sed 's/./*/g'
