# This is a basic workflow to help you get started with Actions

name: Exercicio_1_variaveis_output

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          echo "Instalando as dependências"

      # Runs a set of commands using the runners shell
      - name: Execute tests
        run: |
          echo "Executando os testes do sistema"
  generate:
    needs: build
    runs-on: ubuntu-latest
    outputs: 
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compute version
        id: set-version
        run: |
          VERSION="1.2.3"
          echo "A versão do sistema é $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Variavel de ambiente
        run: |
          echo "APP_ENV=production" >> "$GITHUB_ENV"
          echo "${APP_ENV}"
  deploy:
    needs: generate
    runs-on: ubuntu-latest
    env:
      VERSION: ${{needs.generate.outputs.version}}
    steps:
      - name: Deploy simulation
        run: |
          echo "Implantando a versão ${VERSION} no ambiente de ${APP_ENV}"
          




    
